#' Simulate data based on posterior distribution
#'
#' This function allows you to get fixed scaling correction factor HO for lavaan model to mimic Mplus
#' @param model.Posterior.all the posterior distribution generated by R2jags
#' @param iternum number of interation for simulating data
#' @keywords lavaan scale_factor
#' @export
#' @examples
#' ppmc_simData(model.Posterior.all, iternum)
#'
#' @return simData.list


ppmc_simData <- function(model.Posterior.all, iternum, data){
  # create a placeholder for simulated data list
  simData.list <- array(NA, dim = c(iternum, nrow(data), ncol(data)))

  # Step1: extract parameter from model.Posterior.all : mu, lambda, psi, phi


  # Step2: create mean vector and covariance matrix based on the paramter


  # Step3: simulate the data based on meanVec and covariance matrix
}
